hostname r1
log syslog informational

ip forwarding
ipv6 forwarding

route ospf
  ospf router-id 10.1.1.1
  network 10.9.9.1/24 area 0.0.0.0
  redistribute connected route-map myroutemap

route ospf6
  ospf router-id 10.1.1.1
  interface eth1 area 0.0.0.0
  redistribute connected route-map myroutemap

ip prefix-list allowedprefixes seq 10 permit 10.1.1.0/24
ipv6 prefix-list allowedprefixes seq 10 permit 2006:db8:1::/64

route-map myroutemap permit 10
  match ip address prefix-list allowedprefixes
  match ipv6 address prefix-list allowedprefixes

interface eth1
  ipv6 ospf6 area 0.0.0.0
